server:
  port: 8092
  servlet:
    context-path: /api/zgd-integration/v1/integrations

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/canevim
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

zgd:
  sms:
    url: http://g.ajanswebsms.com/sms_soap/sms.asmx/send_sms
    username: asisttekno
    password: 100223
    vendor: 10000
    header: CANEViM
    charset: turkish
  identity:
    url: https://tckimlik.nvi.gov.tr/Service/KPSPublic.asmx
  shelter:
    url: "https://servisoagtest.icisleri.gov.tr/Services/Producer/EsbApi/GonulluKonutServisi/GonulluKonutKaydet"
    username: "0978002295908001"
    password: "b47dfdd2d981d0575655b28360c85539"
    apikey: "77E54B8B-F916-4D5D-A3E8-8959E08DFB5C"

