server:
  port: 8092
  servlet:
    context-path: /api/zgd-integration/v1/integrations

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/zorgundostu
    username: test
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect

zgd:
  sms:
    url: http://g.ajanswebsms.com/sms_soap/sms.asmx/send_sms
    username: asisttekno
    password: 100223
    vendor: 10000
    header: ZORGUNDOSTU
    charset: turkish
  identity:
    url: https://tckimlik.nvi.gov.tr/Service/KPSPublic.asmx
  shelter:
    url: https://servisoagtest.icisleri.gov.tr/Services/Producer/EsbApi/GonulluKonutServisi/GonulluKonutKaydet

